# Snorby Database Configuration
#
# Please set your database password/user below
# NOTE: Indentation is important.
#
snorby: &snorby
  adapter: mysql
  username: snorby
  password: # Example: password: "s3cr3tsauce"
  host: localhost

development:
  database: snorby_development
  <<: *snorby

test:
  database: snorby_test
  <<: *snorby

production:
  database: snorby
  <<: *snorby
